### ISSUE TITLE
2.2.4.1 - Correct wording for TLS exporter value

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#41]
On January 1, 2020, Jim wrote: 
2.2.4.1 - In my view it is not the secret, but the content that is being
obtained from the TLS exporter.  That is one is signing (or MACing) the
exporter value not using that value to compute a MAC on something else.
While it is true that only the two parties know that value, exposure to a
third party does not lead to a compromise.

**Comment by ciseng** [comment]
Daniel commented: 
<mglt>Just to make sure I follow, the secret is signed or MACed without being
sent. The secret is not used to derive the key used to the signature or MAC.
Instead this key is in the access token.  If I am correct, the use of MAC or
signature is defined by the PoP symmetric or asymmetric. Correct ? I believe
the text could be clearer.  </mglt>

**Comment by ciseng** [comment]
Changed the word secret to content. It does say the content is signed or MACed, and sent in the Authentication Data.  Rejigged the wording that it is more clear. 
Added into token validation HS256 and RS256 are mandatory to implement.

**Comment by jimsch** [comment]
RS256 is an interesting choice, by and large the IETF is going with Ed25519 for signature algorithms at this point although a large number are still stuck with ECDSA w/ P-256.

**Comment by ciseng** [comment]
I lapsed there, will correct. Is it correct usage to just say Ed25519 or ecdsa-sha512 when defining in text.

**Comment by ciseng** [comment]
Changed to Ed25519.
