### ISSUE TITLE
Section 6. Explicitly say MQTT v5 supports MQTT v3.1.1 method as well

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#45]
Januar 1, 2020, Jim wrote: 
It is not clear to me if the authentication method described in this
section is permitted with MQTT v5 or not.  It does not say, but it appears
to be a true statement.  This should probably be explicit.

**Comment by ciseng** [comment]
Added to that section: MQTT v.5 brokers MAY implement this method.

I expect this is a way  MQTTv5 servers may use to support MQTT v3.1 clients?? But not sure the extent that is possible with the rest of the MQTT protocol.

**Comment by jimsch** [comment]
Based on my reading of things you are in the situation where you support v.5 or you support v3.1 or you do a dual stack in order to support both.  The code in the server I am playing with to support both at the same time ends up in a situation where some stuff just gets "lost" during the message encoding process if you are down grading to v3.1.  

A v3.1 client that just says - lets just ask for v.5 is going to get problems when messages come in that it is unable to correctly decode.

**Comment by ciseng** [comment]
I was thinking brokers that want to support v3.1.1 clients would implement dual-stack support. 

The case v3.1.1. client says its v.5 in CONNECT, this should not be allowed. But if it happens, if the client sets username and password fields, they should get the same behaviour in terms of authentication.  The only issues for not being able to decode would be authentication error messages; but then, maybe it is better if we add that if the username/password fields are set; the broker should default to disconnecting the client if an authorisation error happens.  

If they do not set username and password fields, then the server would look for AUTH data, and would not find it - because MQTT v5 connect packet is different than MQTT v3.1.1. data this would create parsing issues... I expect the broker would reject this packet... but this would be a real problem.

Could you say more on what stuff is lost during the message encoding, when client is version 3.1.1?

**Comment by jimsch** [comment]
So here are two examples:

1. https://github.com/chkr1011/MQTTnet/pull/885 has changed the system so if the server sets a user property on the message, it gets dropped by the v3.1 encoder rather than having the encoder throw an exception about the property.  
2.  The same code base also maps from the set of v5 extended error messages back to the v3 error messages in some cases.

**Comment by ciseng** [comment]
We are still assuming clients v3.1.1 asked for v5, right? Then, yes, both would be a problem if MQTT v.3.1.1 client asked for v5 but cannot parse the fields.

When clients say they do v5 we assume 
1. For AS discovery, they can parse the user properties field. 
2. Mapping down may be a problem depending on how it's done - e.g, how PubacK with not authorised error code mapped down - v3.1. does not have reason codes for PUBACKs. If this ends up like a "silent drop", i.e., the client receives a Puback - sees it as confirmation that its message is received, but then broker does not relay its message due to authorisation problem. The client cannot learn that. That's why we disconnect v3.1 clients, and it's important to know that they are v3.1.

Should the profile explicitly say, it expects implementations do
1) v5-only server serving v5-only clients.  (this does not stop v5-server to implement the reduced protocol interactions for v5 clients - this feature setting flags in CONNECT differently and does not interfere with other settings.)
2) v3.1-only server serving v3.1-only clients
3)  v5/v3.1 dual server serving v5 or v3.1.1 clients. It is expected that v3.1.1 clients only expect reduced set.

**Comment by jimsch** [comment]
So the only question left is:  I have a v3.1 client and it works just fine.  I link with a new library and that library knows how to deal with v5 and just internally swallows things the client does not ask for.  Does the client need to upgrade the authentication method.  I think that the answer is probably no so yes a v5 server supports the v3.1 authentication method.

**Comment by ciseng** [comment]
So with this library, the originally 3.1 client connects to the server as v5? So, yes, using the same authentication method to pass the token (with username and password) would work. 
When the token expires, I assume also this library is able to parse the authentication errors returned by PUBACK etc., which makes the client, most probably, disconnect. It cannot try to re-authenticate as that assumes a v5, and being able to use AUTH.

**Comment by ciseng** [comment]
In the interim,
Broker MAY support dual stack for V3.1.1 clients. 
and v5 clients should not use the v3.1.1 method.

This would simplify the interoperability discussion.

**Comment by ciseng** [comment]
Added to Section 2.2.3:
"An MQTT v5 RS MAY support token transport using username and password to provide a security option for MQTT v3.1.1 clients, as described in  Section 6."

Added to Section 6:
"This section describes a reduced set of protocol interactions for the MQTT v3.1.1 Client.
 An MQTT v5 Broker MAY implement these interactions for the MQTT v3.1.1 clients; MQTT v5 clients are NOT RECOMMENDED to use the flows described in this section. "
