### ISSUE TITLE
Section 2.4.3 - explain AS creation hints as CONNACK user property. 

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#46]
On January 1, Jim wrote: 
2.2.4.3 - What is the name of the user property that is being returned here?

[CS] This is under-defined. It should say, the name pairs follow the same optional name, value parameters for AS request creation hints as defined in the core document. There could be multiple user properties in a CONNACK, one needs to make sure the size of the message does not grow beyond the Maximum Packet Size specified by the client.

**Comment by jimsch** [comment]
I was assuming that there was only one property, but that it was a JSON string that encoded the properties.  Make sure that what ever you do the user property names are some how scoped to the profile.   I don't know what, if anything, the MQTT people were thinking about keeping these names unique or non-conflicting.

**Comment by ciseng** [comment]
+1

Do not know why it's allowed to have the same name appear more than once either.

**Comment by ciseng** [comment]
Decided not to add multiple name-value pairs; added the following text to the draft:
The User Property is a UTF-8 string pair, composed of a name and a value. The name of the User Property MUST be set to "ace_as_hint". The value of the user property is a UTF-8 encoded JSON string containing the mandatory "AS" parameter,  and the optional parameters "audience", "kid", "cnonce", and "scope" as defined  in the Section 5.1.2 of <xref target="I-D.ietf-ace-oauth-authz">the ACE framework</xref>.

**Comment by jimsch** [comment]
I think this looks good.

**Comment by ciseng** [comment]
OK, will close then.

**Comment by jimsch** [comment]
You did not state the property name in the Editors copy of the document.

**Comment by ciseng** [comment]
It is in the submitted v4: "The name of the User Property MUST be set to "ace_as_hint"."
I do not close issues if they are not agreed and fixed in the submitted version. Also, the source file is not ahead of the submitted version at the moment.
The issue is in the Editors copy - will fix.
