### ISSUE TITLE
Paragraph 4 section 1 - There is some missing text here

### ISSUE THREAD

**Issue by jimsch** [ace-wg/mqtt-tls-profile#48]
This document describes how to authorise the following exchanges between the Clients and the Broker. the CoAP Pub-Sub Profile [I-D.palombini-ace-coap-pubsub-profile].

**Comment by ciseng** [comment]
Again correct in the submitted version 4: "This functionality may be
   implemented using the proposal outlined in the CoAP Pub-Sub Profile
   [I-D.ietf-ace-pubsub-profile]. "
