### ISSUE TITLE
Figure 2 has an error

### ISSUE THREAD

**Issue by jimsch** [ace-wg/mqtt-tls-profile#49]
I think that the string "empty or" should be removed from this diagram.  If you say that the method is ace and don't supply any data then the server cannot know who it is authenticating using the ace method.

~~~ 
      |          Auth. Method (0x15) | 'ace'                 |
       |          Auth. Data (0x16)   | empty or token or     |
       |                                token + PoP data      |
~~~

**Comment by jimsch** [comment]
found it

**Comment by ciseng** [comment]
We should say AUTH. Data not present in the figure to align with text.

**Comment by ciseng** [comment]
Removed "empty" from the figure.
