### ISSUE TITLE
Need to have a length in section 2.2.4.2

### ISSUE THREAD

**Issue by jimsch** [ace-wg/mqtt-tls-profile#50]
I need to have the length of the token for both the challenge response and the token+proof version.  I don't think it is possible to tell the difference between the length being there and it not being there.

**Comment by ciseng** [comment]
True, the length of token should be included in the request so that the RS can invoke the right method. If it cannot find anything beyond the token, then it starts the challenge-response flow. 
Will fix.

**Comment by ciseng** [comment]
The commit above adds token length to the Authentication Data for the challenge/response flow.
