### ISSUE TITLE
Clean session requirement - change MUST to SHOULD

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#52]
In the interim, we discussed MUST is too strict when efficiency is considered. Therefore, we will drop this to SHOULD, and other SHOULDs around how the server keeps state, and for how long, and how it deals with any pending messages etc.

**Comment by ciseng** [comment]
Added new text:
"In MQTT v5, the Client signals a clean session (i.e., the session does not continue an existing session), by setting the Clean Start Flag to 1 and, the Session Expiry Interval to 0 in the CONNECT message. In this profile, the Broker SHOULD always start with a clean session regardless of how these parameters are set."
"
If necessary, the Broker MAY support session continuation, and hence, maintain and use client state from the existing session. The client state MAY include token and its introspection result (for reference tokens) in addition to the MQTT session state. When reconnecting to the Broker, the Client MUST still provide a token, as well as setting the Clean Start to 0 and supplying a Session Expiry interval in the CONNECT message. The Broker MUST perform proof-of-possession validation on the provided token.  If the token matches the stored state, the Broker MAY skip introspecting a token by reference, and use the stored introspection result.  Continuing, both the Client and Broker MUST resend any unacknowledged PUBLISH packets (where QoS > 0) and PUBREL packets. The Broker MUST still verify the Client is authorized to receive or send these packets. When a Client connects with a long Session Expiry Interval, the Broker may need to maintain Client's MQTT session state after it disconnects for an extended period. Brokers SHOULD implement administrative policies to limit misuse.
"
Commit bd4589ce45ee1f938b9f3292116759cc6536b631

**Comment by ciseng** [comment]
Added also to MQTT 3.1.1 handling of Clean Start Flag.

**Comment by jimsch** [comment]
looks good
