### ISSUE TITLE
Section 2.2.2 - para #1 - s/using client authentication/using server authentication/

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#56]
Jim's review:
* Section 2.2.2 - para #1 - s/using client authentication/using server
authentication/  If we are doing MQTT as the default then the server not the
client is authenticated here.  You may not want to have lost the potentially
here.

**Comment by ciseng** [comment]
What I meant here was this: Given that the client pushed the token using authz-info,we expect it to use authenticate itself over TLS next time it connects (otherwise it would have carried the token in the MQTT connect). I will fix it as using client authentication over TLS (i.e, TLS:Known(RPK/PSK)-MQTT:none) but wanted to check first if I missed your meaning.

**Comment by jimsch** [comment]
That would eliminate the case I was worried about.
