### ISSUE TITLE
Clarify Broker hosting public topics, and clients connecting without authorisation

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#82]
AD-Review: 05/08/2021 

Action: Clarify that Broker can host public topics, and accept clients without authorisation. 

Original draft:
"TLS:Anon-MQTT:None": This option is used only for the topics that
      do not require authorization, including the "authz-info" topic.

Comment:
Are there topics other than "authz-info" that don't require
authorization?  We might need to add some heading language to the earlier
statement that "Client and the Broker MUST perform mutual
authentication" if so.

CS: I think the Git pull request already added some text around for mutual authentication. 
I will clarify that the Broker can host public topics, and can have clients that consume only topics.

**Comment by kaduk** [comment]
This looks good in the -13.
