### ISSUE TITLE
Fix MQTT Connect Example Figure

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#83]
AD-Review: 05/08/2021

Action: Fix the issues in the two Comments. 

Original Draft:
 +------------------------------------------------------+
          |CPT=1 | Rsvd.|Remaining len.| Protocol name len. = 4  |
          +------------------------------------------------------+

Comment:
Figure 2 appears to show that the Remaining Length field of the fixed
header occupies a single octet, but IIUC it's encoded as a variable byte
integer.  Fixing that would also let us put the separator that appears
after it on a proper byte boundary.

Original draft:

          |                      'M' 'Q' 'T' 'T'                 |
          +------------------------------------------------------+

This figure does not show the two-byte length prefix for the string.

**Comment by kaduk** [comment]
Fixed in the -13.
