### ISSUE TITLE
Fix the MQTT Clean Session Description

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#84]
AD-Review - 05/08/2021

Action: Implement the fix in my comment.

Original draft:
  In MQTT v5.0, the Client signals a clean session (i.e. the session
   does not continue an existing session), by setting the Clean Start
   Flag to 1 and, the Session Expiry Interval to 0 in the CONNECT
   message.  [...]

Comment:
I don't understand why setting the Session Expiry Interval to 0 is
needed to produce a clean session.  As I understand it, setting this
interval to 0 merely directs the server to not store session state after
the client disconnects from this session, which is unrelated to whether
or not this is a new session or a reused session.

**Comment by ciseng** [comment]
[CS: This was when we switched from MQTT v3.1 to induce MQTT v5 in the draft. 
We were looking for some equivalence between two specs and MQTTv5 had:
"Setting of Clean Start to 1 and Session Expiry Interval to 0 is equivalent in MQTT v3.1.1 of setting Clean Session to 1."
But we should acknowledge that this got separated and a clean start is the way to signal to start a new session. Will fix.]

[CS: yes, you are right. the CONNACK can set the session expiry interval to 0. 
Actually, then it doesn't matter what clean start flag is. 
I will change to the "Session Expiry Interval SHOULD be set to 0" so that no session state is kept. 
And yes the server can override the client's session expiry interval in connect by
sending a different value in connack. ]

Ben: Thanks for confirming that I was reading the MQTT spec properly (in this
instance, at least)!  This proposal sounds good to me.


[CS: Overspecified for current connection? As this is something that is communicated in the CONNECT, my preference would be to include it and be clear about it. At the moment, the client is allowed to provide a session expiry interval (to say for how long it wants the session state to be kept at the broker),  but the server can connack a different value. It may actually be better to recommend a broker to always dictate session expiry in connack and not accept client value? ]

Ben - I think we probably should focus more on broker behavior, yes.
So this could be "client SHOULD set to zero" and "broker MUST dictate
expire in connack" as you suggest.

[CS:This will be revised, but the Broker can signal if it can support continuing a session or not by sending a CONNACK with session expiry interval 0.]

Ben - Yup, and that's fine -- I have no problem telling the broker that it will
not actually create new sessions, just with requiring it to put bits on the
wire that OASIS says to not do.

[CS: Will clarify the Session Expiry Interval, which may lead to keeping state.]

**Comment by ciseng** [comment]
Fixed all mixups - allowed Broker to continue session, but also that it is not willing to do it by Setting session expiry interval to 0.

**Comment by kaduk** [comment]
I think this is fixed in the -13.
