### ISSUE TITLE
Will topic authorisation

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#91]
AD-Review: 05/08/2021
Action: Apply fix in my later comment. 

Original draft:
 If the Will Flag is set, then the Broker MUST check that the token
   allows the publication of the Will message (i.e. the Will Topic
   filter is in the scope array).

Comment:
We might want to say a little more about when this check happens.  My
intuition is that it occurs during the CONNECT processing where the
actual Will message is provided, and that the connection would be
rejected if the Will message is unauthorized.  But this section is
titled "Authorizing PUBLISH and SUBSCRIBE Messages", so one might be
forgiven for assuming that CONNECT is out of scope...

**Comment by ciseng** [comment]
[CS: I assumed the check will happen when the Will message needs to be published (information about the Will topic is in the CONNECT).
And the Broker will refuse to publish if it is not covered in the token. This can be changed to checking in CONNECT but then, we add "Will message not authorised" as a reason to refuse Connection with the rationale that even if it is not an actual publication, it may result in publishing a message (the will) in future. 
(I've written more on this in "Will do" section below, because it came up in multiple places, and I did not want to repeat the same discussion)]
 
[CS: I've put a note on this in discussion. The client does supply the will in the message, but it's for a future publication;
it may never be published. We can choose to reject that in CONNECT, or when the time comes.I  am fine either way to add a CONNECT failure
due to Will being out of scope.]

[CS: I agree. This check needs to happen during CONNECT, and fail the connection with Not Authorised.
Brokers can use a reason string to give more diagnostic information. 
Similarly, Server does include Will-Topic check to re-authorisation, and triggers DISCONNECT if it cannot fulfill the Will. 

I must have gotten myself confused as this should have been the intention from the beginning as I have the following text in the draft:
"If the Will Flag is set, then the Broker MUST check that the token allows the publication of the Will message (i.e. the Will Topic filter is in the scope array)." - which is in the wrong place, and should be in CONNECT. 
Still, it was under-specified, ie. if the check fails, it leads to Not Authorised etc.
]

**Comment by kaduk** [comment]
I think this is fixed in the -13.
