### ISSUE TITLE
Subscribe Topic wildcard - token scope matching

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#92]
AD-Review: 05/08/2021
Action: Clarify (also with an example)

Original draft:
Section 3.3

   On receiving the SUBSCRIBE message, the Broker MUST use the type of
   message (i.e.  SUBSCRIBE) and the Topic Filter in the message header
   to match against the scope field of the stored token or introspection
   result.  The Topic Filters MUST be equal or a subset of at least one
   of the 'topic_filter' fields in the scope array found in the Client's
   token.

Comment:
I suggest being very explicit about whether the wildcards in the token
scope are expanded as part of matching the topic filter in the request,
or if the SUBSCRIBE message must use topic filters that match
byte-for-byte the permissions granted by the token.

**Comment by kaduk** [comment]
Fixed in -13.
