### ISSUE TITLE
ACE token/MAC parsing in MQTT v.3.1.1 CONNECT

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#93]
AD-Review 05/08/2021
Action: clarify, and give an example.

Original draft:
The CONNECT in MQTT v3.1.1 does not have a field to indicate the
   authentication method.  To signal that the Username field contains an
   ACE token, this field MUST be prefixed with 'ace' keyword, which is
   followed by the access token.  [...]

Connect:
An example of what this looks like would be helpful.  It sounds like we
just take the first three bytes for the sentinel and then go directly to
the access token, vs having some kind of "separator" as part of the
sentinel value.

**Comment by kaduk** [comment]
Fixed in -13.
