### ISSUE TITLE
Fix TLS-Exporter-Label-Registry fields

### ISSUE THREAD

**Issue by ciseng** [ace-wg/mqtt-tls-profile#94]
AD-Review 05/08/2021:

Action: Implement the comment.

Original draft:
Section 7.1
   This document registers 'EXPORTER-ACE-MQTT-Sign-Challenge'
   (introduced in Section 2.2.4.1 in this document) in the TLS Exporter
   Label Registry [RFC8447].

Comment:
We need to specify the other columns in the registry.
I think we can have:
DTLS-OK: Y
Recommended: Y
Reference: [this document]

**Comment by kaduk** [comment]
Fixed in -13
